$hyprDir = .
source = $hyprDir/monitors.conf
source = $hyprDir/programs.conf
source = $hyprDir/env.conf
source = $hyprDir/look-and-feel.conf
source = $hyprDir/input.conf
source = $hyprDir/keybindings.conf
source = $hyprDir/windowrules-and-workspaces.conf

