###### Programs
$terminal = alacritty
$fileManager = dolphin
$menu = rofi --show drun
$bar = waybar
$browser_main = zen
$browser_dev = chromium

###### Actions
$reload_bar = pkill $bar; $bar &
$snip = 

###### Autostart
exec-once = hyprpaper
exec-once = $bar
exec-once = cursor-clip --daemon
exec-once = swaync

